### ISSUE TITLE
design: モダンデザインシステム基盤とトークン定義

### ISSUE THREAD

**Issue by sasazame** [sasazame/todo-app-frontend#8]
一貫性のあるモダンなUIを実現するためのデザインシステム基盤を構築する。

**実装内容**:
- デザイントークン定義（色、フォント、スペーシング、影等）
- CSS Variables / Styled-components テーマ設定
- コンポーネントライブラリ基盤
- Storybook導入（コンポーネントカタログ）
- レスポンシブブレイクポイント定義

**受け入れ条件**:
- [ ] 統一されたカラーパレットが定義される
- [ ] タイポグラフィシステムが整備される
- [ ] グリッドシステムが構築される
- [ ] Storybookでコンポーネントが確認できる
- [ ] ダークモード対応基盤が整備される

**デザイントークン例**:
```css
:root {
  /* Primary Colors */
  --color-primary-50: #f0f9ff;
  --color-primary-500: #3b82f6;
  --color-primary-900: #1e3a8a;
  
  /* Neutral Colors */
  --color-neutral-50: #f8fafc;
  --color-neutral-500: #64748b;
  --color-neutral-900: #0f172a;
  
  /* Typography */
  --font-family-sans: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
  --font-size-xs: 0.75rem;
  --font-size-lg: 1.125rem;
  
  /* Spacing */
  --spacing-1: 0.25rem;
  --spacing-4: 1rem;
  --spacing-16: 4rem;
  
  /* Shadows */
  --shadow-sm: 0 1px 2px 0 rgb(0 0 0 / 0.05);
  --shadow-lg: 0 10px 15px -3px rgb(0 0 0 / 0.1);
  
  /* Border Radius */
  --radius-sm: 0.375rem;
  --radius-lg: 0.75rem;
}
```

**デザインコンセプト**:
- **ミニマル & クリーン**: 余白を活用した洗練されたレイアウト
- **モダン**: 現代的なUI/UXトレンドに準拠
- **アクセシブル**: WCAG 2.1 AA準拠の色彩コントラスト
- **レスポンシブ**: モバイルファーストアプローチ
